#!/bin/bash

bridge=${INTERFACE:0:-2}br

ip addr add 0.0.0.0 dev ${INTERFACE}
ip link add name ${bridge} type bridge
ip link set dev ${bridge} up
ip link set dev ${INTERFACE} master ${bridge}
ip link set dev ${INTERFACE} up
