#!/bin/sh

bridge=${INTERFACE}br

#ip addr del 0.0.0.0 dev ${INTERFACE}
#ip link set dev ${INTERFACE} promisc off
#ip link set dev ${INTERFACE} down
#ip link set dev ${INTERFACE} nomaster
#ip link delete $bridge type bridge
