#!/bin/bash

bridge=${INTERFACE}br

ip link add name ${bridge} type bridge
ip link set dev ${bridge} up
ip addr add 0.0.0.0 dev ${INTERFACE}
ip link set dev ${INTERFACE} promisc on
ip link set dev ${INTERFACE} up
ip link set dev ${INTERFACE} master ${bridge}
